### ISSUE TITLE
关于模拟器下载

### ISSUE THREAD

**Issue by johnson619** [massyao/Health-Code-Simulator#1]
你好，请问哪里可以下载测试？

**Comment by johnson619** [comment]
我按照教程做好以后。 打开PAGE  时间不会自动更新。。 总是 01-04 12：59：59

**Comment by massyao** [comment]
issue fixed, just use the new code

**Comment by johnson619** [comment]
got it , thanks, i will try the new code later

massyao ***@***.***> 于2022年1月8日周六 14:37写道：
